# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jargon/school/eden

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jargon/school/eden

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jargon/school/eden/CMakeFiles /home/jargon/school/eden//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jargon/school/eden/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Eden

# Build rule for target.
Eden: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Eden
.PHONY : Eden

# fast build rule for target.
Eden/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/build
.PHONY : Eden/fast

Character.o: Character.cpp.o
.PHONY : Character.o

# target to build an object file
Character.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Character.cpp.o
.PHONY : Character.cpp.o

Character.i: Character.cpp.i
.PHONY : Character.i

# target to preprocess a source file
Character.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Character.cpp.i
.PHONY : Character.cpp.i

Character.s: Character.cpp.s
.PHONY : Character.s

# target to generate assembly for a file
Character.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Character.cpp.s
.PHONY : Character.cpp.s

Enemy.o: Enemy.cpp.o
.PHONY : Enemy.o

# target to build an object file
Enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Enemy.cpp.o
.PHONY : Enemy.cpp.o

Enemy.i: Enemy.cpp.i
.PHONY : Enemy.i

# target to preprocess a source file
Enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Enemy.cpp.i
.PHONY : Enemy.cpp.i

Enemy.s: Enemy.cpp.s
.PHONY : Enemy.s

# target to generate assembly for a file
Enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Enemy.cpp.s
.PHONY : Enemy.cpp.s

Game.o: Game.cpp.o
.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i
.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s
.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Game.cpp.s
.PHONY : Game.cpp.s

Healthbar.o: Healthbar.cpp.o
.PHONY : Healthbar.o

# target to build an object file
Healthbar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Healthbar.cpp.o
.PHONY : Healthbar.cpp.o

Healthbar.i: Healthbar.cpp.i
.PHONY : Healthbar.i

# target to preprocess a source file
Healthbar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Healthbar.cpp.i
.PHONY : Healthbar.cpp.i

Healthbar.s: Healthbar.cpp.s
.PHONY : Healthbar.s

# target to generate assembly for a file
Healthbar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Healthbar.cpp.s
.PHONY : Healthbar.cpp.s

Lilith.o: Lilith.cpp.o
.PHONY : Lilith.o

# target to build an object file
Lilith.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Lilith.cpp.o
.PHONY : Lilith.cpp.o

Lilith.i: Lilith.cpp.i
.PHONY : Lilith.i

# target to preprocess a source file
Lilith.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Lilith.cpp.i
.PHONY : Lilith.cpp.i

Lilith.s: Lilith.cpp.s
.PHONY : Lilith.s

# target to generate assembly for a file
Lilith.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Lilith.cpp.s
.PHONY : Lilith.cpp.s

MovingObject.o: MovingObject.cpp.o
.PHONY : MovingObject.o

# target to build an object file
MovingObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/MovingObject.cpp.o
.PHONY : MovingObject.cpp.o

MovingObject.i: MovingObject.cpp.i
.PHONY : MovingObject.i

# target to preprocess a source file
MovingObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/MovingObject.cpp.i
.PHONY : MovingObject.cpp.i

MovingObject.s: MovingObject.cpp.s
.PHONY : MovingObject.s

# target to generate assembly for a file
MovingObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/MovingObject.cpp.s
.PHONY : MovingObject.cpp.s

Player.o: Player.cpp.o
.PHONY : Player.o

# target to build an object file
Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Player.cpp.o
.PHONY : Player.cpp.o

Player.i: Player.cpp.i
.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s
.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Player.cpp.s
.PHONY : Player.cpp.s

Projectile.o: Projectile.cpp.o
.PHONY : Projectile.o

# target to build an object file
Projectile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Projectile.cpp.o
.PHONY : Projectile.cpp.o

Projectile.i: Projectile.cpp.i
.PHONY : Projectile.i

# target to preprocess a source file
Projectile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Projectile.cpp.i
.PHONY : Projectile.cpp.i

Projectile.s: Projectile.cpp.s
.PHONY : Projectile.s

# target to generate assembly for a file
Projectile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Projectile.cpp.s
.PHONY : Projectile.cpp.s

SpriteObject.o: SpriteObject.cpp.o
.PHONY : SpriteObject.o

# target to build an object file
SpriteObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/SpriteObject.cpp.o
.PHONY : SpriteObject.cpp.o

SpriteObject.i: SpriteObject.cpp.i
.PHONY : SpriteObject.i

# target to preprocess a source file
SpriteObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/SpriteObject.cpp.i
.PHONY : SpriteObject.cpp.i

SpriteObject.s: SpriteObject.cpp.s
.PHONY : SpriteObject.s

# target to generate assembly for a file
SpriteObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/SpriteObject.cpp.s
.PHONY : SpriteObject.cpp.s

Wall.o: Wall.cpp.o
.PHONY : Wall.o

# target to build an object file
Wall.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Wall.cpp.o
.PHONY : Wall.cpp.o

Wall.i: Wall.cpp.i
.PHONY : Wall.i

# target to preprocess a source file
Wall.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Wall.cpp.i
.PHONY : Wall.cpp.i

Wall.s: Wall.cpp.s
.PHONY : Wall.s

# target to generate assembly for a file
Wall.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Wall.cpp.s
.PHONY : Wall.cpp.s

Worm.o: Worm.cpp.o
.PHONY : Worm.o

# target to build an object file
Worm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Worm.cpp.o
.PHONY : Worm.cpp.o

Worm.i: Worm.cpp.i
.PHONY : Worm.i

# target to preprocess a source file
Worm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Worm.cpp.i
.PHONY : Worm.cpp.i

Worm.s: Worm.cpp.s
.PHONY : Worm.s

# target to generate assembly for a file
Worm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/Worm.cpp.s
.PHONY : Worm.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Eden.dir/build.make CMakeFiles/Eden.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Eden"
	@echo "... Character.o"
	@echo "... Character.i"
	@echo "... Character.s"
	@echo "... Enemy.o"
	@echo "... Enemy.i"
	@echo "... Enemy.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... Healthbar.o"
	@echo "... Healthbar.i"
	@echo "... Healthbar.s"
	@echo "... Lilith.o"
	@echo "... Lilith.i"
	@echo "... Lilith.s"
	@echo "... MovingObject.o"
	@echo "... MovingObject.i"
	@echo "... MovingObject.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... Projectile.o"
	@echo "... Projectile.i"
	@echo "... Projectile.s"
	@echo "... SpriteObject.o"
	@echo "... SpriteObject.i"
	@echo "... SpriteObject.s"
	@echo "... Wall.o"
	@echo "... Wall.i"
	@echo "... Wall.s"
	@echo "... Worm.o"
	@echo "... Worm.i"
	@echo "... Worm.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

